//! The conversation an Agent-view session had before the app restarted.
//!
//! A restored Agent-view session starts Claude again with `--resume <id>`:
//! Claude keeps the context, but its stream only carries what happens from
//! then on, so the view would start empty. Claude Code keeps the whole
//! conversation in `<config>/projects/<project folder>/<id>.jsonl`; this
//! reads it back as the same `user` / `assistant` events the view folds, so
//! the earlier messages are drawn again.

use std::io::{Read, Seek, SeekFrom};
use std::path::{Path, PathBuf};

use serde_json::{json, Value};

/// Read at most this much of the end of a transcript: a long conversation
/// still comes back quickly, with its latest part.
const MAX_TRANSCRIPT_BYTES: u64 = 8 * 1024 * 1024;

/// Claude Code's configuration folder: `CLAUDE_CONFIG_DIR`, else `~/.claude`.
fn claude_config_dir() -> Option<PathBuf> {
    config_dir_from(std::env::var_os("CLAUDE_CONFIG_DIR"), dirs::home_dir())
}

fn config_dir_from(
    configured: Option<std::ffi::OsString>,
    home: Option<PathBuf>,
) -> Option<PathBuf> {
    match configured {
        Some(dir) if !dir.is_empty() => Some(PathBuf::from(dir)),
        _ => home.map(|h| h.join(".claude")),
    }
}

/// The earlier conversation of `session_id` from the transcripts under `projects`.
fn history_in(projects: &Path, working_dir: &str, session_id: &str) -> Result<Vec<Value>, String> {
    match find_transcript(projects, working_dir, session_id) {
        Some(path) => read_history(&path, MAX_TRANSCRIPT_BYTES).map_err(|e| e.to_string()),
        None => Ok(Vec::new()),
    }
}

/// A Claude session id as Claude writes it (a UUID): nothing that could
/// name another path.
fn is_session_id(id: &str) -> bool {
    !id.is_empty() && id.len() <= 64 && id.chars().all(|c| c.is_ascii_hexdigit() || c == '-')
}

/// Where Claude keeps the transcript of `session_id`, started in
/// `working_dir`: the project folder named after that folder (as the shell
/// gave it, or resolved), else whichever project folder holds the file (the
/// id is unique, and long folder names get a hash suffix).
pub(crate) fn find_transcript(
    projects_dir: &Path,
    working_dir: &str,
    session_id: &str,
) -> Option<PathBuf> {
    if !is_session_id(session_id) || !projects_dir.is_dir() {
        return None;
    }
    let file = format!("{session_id}.jsonl");
    let mut folders = vec![working_dir.to_string()];
    if let Ok(resolved) = dunce::canonicalize(working_dir) {
        folders.push(resolved.to_string_lossy().to_string());
    }
    for folder in folders.iter().filter(|f| !f.is_empty()) {
        let candidate = projects_dir
            .join(crate::transcript::claude_project_dir_name(folder))
            .join(&file);
        if candidate.is_file() {
            return Some(candidate);
        }
    }
    std::fs::read_dir(projects_dir)
        .ok()?
        .flatten()
        .map(|entry| entry.path().join(&file))
        .find(|candidate| candidate.is_file())
}

/// The end of the file (whole lines only), at most `max` bytes.
fn read_tail(path: &Path, max: u64) -> std::io::Result<String> {
    let mut f = std::fs::File::open(path)?;
    let len = f.metadata()?.len();
    let start = len.saturating_sub(max);
    f.seek(SeekFrom::Start(start))?;
    let mut bytes = Vec::new();
    f.read_to_end(&mut bytes)?;
    if start > 0 {
        // Started mid-line: drop that partial line.
        match bytes.iter().position(|b| *b == b'\n') {
            Some(nl) => {
                bytes.drain(..=nl);
            }
            None => bytes.clear(),
        }
    }
    Ok(String::from_utf8_lossy(&bytes).into_owned())
}

/// Text Claude Code writes as a user turn that the person did not type in
/// the composer: slash-command and `!` shell plumbing, background-task
/// notices, interruption notes.
fn is_plumbing(text: &str) -> bool {
    let t = text.trim_start();
    [
        "<command-name>",
        "<command-message>",
        "<command-args>",
        "<local-command-stdout>",
        "<local-command-stderr>",
        "<local-command-caveat>",
        "<bash-input>",
        "<bash-stdout>",
        "<bash-stderr>",
        "<task-notification>",
        "[Request interrupted by user",
        "Caveat: The messages below were generated by the user while running local commands",
    ]
    .iter()
    .any(|p| t.starts_with(p))
}

fn epoch_ms(record: &Value) -> Option<i64> {
    let ts = record.get("timestamp")?.as_str()?;
    chrono::DateTime::parse_from_rfc3339(ts)
        .ok()
        .map(|d| d.timestamp_millis())
}

/// One transcript line as the event the view folds, or None when it is not
/// part of the conversation the person saw (sub-agent side chains, notes
/// Claude Code adds for itself, slash-command plumbing, summaries).
pub(crate) fn history_event(record: &Value) -> Option<Value> {
    let kind = record.get("type")?.as_str()?;
    if record.get("isSidechain").and_then(Value::as_bool) == Some(true) {
        return None;
    }
    let ts = epoch_ms(record);
    match kind {
        "assistant" => {
            let message = record.get("message")?;
            message.get("id")?.as_str()?;
            message.get("content")?.as_array()?;
            Some(json!({
                "type": "assistant",
                "message": message,
                "uuid": record.get("uuid"),
                "parent_tool_use_id": Value::Null,
                "_hermes_history_ts": ts,
            }))
        }
        "user" => {
            if record.get("isMeta").and_then(Value::as_bool) == Some(true)
                || record.get("isCompactSummary").and_then(Value::as_bool) == Some(true)
            {
                return None;
            }
            let message = record.get("message")?;
            let content = match message.get("content")? {
                Value::String(text) => {
                    if text.trim().is_empty() || is_plumbing(text) {
                        return None;
                    }
                    vec![json!({ "type": "text", "text": text })]
                }
                Value::Array(blocks) => {
                    let kept: Vec<Value> = blocks
                        .iter()
                        .filter(|b| match b.get("type").and_then(Value::as_str) {
                            Some("text") => b
                                .get("text")
                                .and_then(Value::as_str)
                                .is_some_and(|t| !t.trim().is_empty() && !is_plumbing(t)),
                            _ => true,
                        })
                        .cloned()
                        .collect();
                    if kept.is_empty() {
                        return None;
                    }
                    kept
                }
                _ => return None,
            };
            Some(json!({
                "type": "user",
                "message": { "role": "user", "content": content },
                "uuid": record.get("uuid"),
                "parent_tool_use_id": Value::Null,
                "_hermes_history_ts": ts,
            }))
        }
        _ => None,
    }
}

/// The conversation in a transcript file, oldest first.
pub(crate) fn read_history(path: &Path, max_bytes: u64) -> std::io::Result<Vec<Value>> {
    let text = read_tail(path, max_bytes)?;
    Ok(text
        .lines()
        .filter_map(|line| serde_json::from_str::<Value>(line).ok())
        .filter_map(|record| history_event(&record))
        .collect())
}

/// The earlier conversation of the Claude session `claude_session_id`
/// started in `working_dir`, as Agent-view events (oldest first). Empty when
/// Claude kept no transcript for it.
#[tauri::command]
pub async fn agent_history(
    working_dir: String,
    claude_session_id: String,
) -> Result<Vec<Value>, String> {
    tokio::task::spawn_blocking(move || match claude_config_dir() {
        Some(config) => history_in(&config.join("projects"), &working_dir, &claude_session_id),
        None => Ok(Vec::new()),
    })
    .await
    .map_err(|e| e.to_string())?
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::fs;

    const ID: &str = "0b5c8f3e-2a1d-4c3b-9e7f-1a2b3c4d5e6f";

    fn line(v: Value) -> String {
        format!("{v}\n")
    }

    fn sample() -> String {
        [
            line(json!({"type": "summary", "summary": "Greeting"})),
            line(json!({"type": "user", "uuid": "u1", "timestamp": "2026-10-05T10:00:00.000Z", "message": {"role": "user", "content": "make greet say hello, world"}})),
            line(json!({"type": "assistant", "uuid": "a1", "timestamp": "2026-10-05T10:00:01.000Z", "message": {"id": "msg_1", "role": "assistant", "content": [{"type": "thinking", "thinking": "Read it first."}]}})),
            line(json!({"type": "assistant", "uuid": "a2", "timestamp": "2026-10-05T10:00:02.000Z", "message": {"id": "msg_1", "role": "assistant", "content": [{"type": "tool_use", "id": "t1", "name": "Bash", "input": {"command": "cat greet.js"}}]}})),
            line(json!({"type": "user", "uuid": "u2", "timestamp": "2026-10-05T10:00:03.000Z", "message": {"role": "user", "content": [{"type": "tool_result", "tool_use_id": "t1", "content": "hello"}]}})),
            line(json!({"type": "user", "uuid": "u3", "isMeta": true, "message": {"role": "user", "content": "Caveat: generated by Claude Code"}})),
            line(json!({"type": "user", "uuid": "u4", "message": {"role": "user", "content": "<command-name>/model</command-name>"}})),
            line(json!({"type": "user", "uuid": "u5", "message": {"role": "user", "content": [{"type": "text", "text": "<task-notification>done</task-notification>"}]}})),
            line(json!({"type": "user", "uuid": "u6", "message": {"role": "user", "content": [{"type": "text", "text": "[Request interrupted by user]"}]}})),
            line(json!({"type": "assistant", "uuid": "a3", "isSidechain": true, "message": {"id": "msg_side", "content": [{"type": "text", "text": "sub-agent"}]}})),
            line(json!({"type": "assistant", "uuid": "a4", "timestamp": "2026-10-05T10:00:04.000Z", "message": {"id": "msg_2", "role": "assistant", "content": [{"type": "text", "text": "Done."}], "stop_reason": "end_turn"}})),
            "not json\n".to_string(),
        ]
        .concat()
    }

    #[test]
    fn the_conversation_comes_back_as_view_events_without_plumbing() {
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("t.jsonl");
        fs::write(&path, sample()).unwrap();
        let events = read_history(&path, MAX_TRANSCRIPT_BYTES).unwrap();
        let kinds: Vec<(&str, &str)> = events
            .iter()
            .map(|e| (e["type"].as_str().unwrap(), e["uuid"].as_str().unwrap()))
            .collect();
        assert_eq!(
            kinds,
            vec![
                ("user", "u1"),
                ("assistant", "a1"),
                ("assistant", "a2"),
                ("user", "u2"),
                ("assistant", "a4")
            ]
        );
        // A typed prompt kept as a string becomes a text block.
        assert_eq!(
            events[0]["message"]["content"],
            json!([{"type": "text", "text": "make greet say hello, world"}])
        );
        // Tool results stay as they are, so the command card gets its output.
        assert_eq!(events[3]["message"]["content"][0]["type"], "tool_result");
        // The time it was said, for the message's clock.
        assert_eq!(
            events[0]["_hermes_history_ts"],
            json!(1_791_194_400_000_i64)
        );
        assert!(events.iter().all(|e| e["parent_tool_use_id"].is_null()));
    }

    #[test]
    fn a_long_transcript_comes_back_from_its_end_in_whole_lines() {
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("t.jsonl");
        let body = sample();
        fs::write(&path, &body).unwrap();
        // Only the last part fits: it starts mid-line, which is dropped.
        let a4_line = body[..body.find("\"a4\"").unwrap()].rfind('\n').unwrap() + 1;
        let tail_len = (body.len() - a4_line + 10) as u64;
        let events = read_history(&path, tail_len).unwrap();
        let uuids: Vec<&str> = events.iter().map(|e| e["uuid"].as_str().unwrap()).collect();
        assert_eq!(uuids, vec!["a4"]);
    }

    #[test]
    fn the_transcript_is_found_by_folder_and_else_by_its_id() {
        let projects = tempfile::tempdir().unwrap();
        let named = projects
            .path()
            .join(crate::transcript::claude_project_dir_name("/work/greet"));
        fs::create_dir_all(&named).unwrap();
        fs::write(named.join(format!("{ID}.jsonl")), "").unwrap();
        assert_eq!(
            find_transcript(projects.path(), "/work/greet", ID),
            Some(named.join(format!("{ID}.jsonl")))
        );

        // Started in another folder (or a long name with a hash suffix): the id finds it.
        let other = projects.path().join("-somewhere-else-1a2b3c");
        fs::create_dir_all(&other).unwrap();
        let other_id = "11111111-2222-3333-4444-555555555555";
        fs::write(other.join(format!("{other_id}.jsonl")), "").unwrap();
        assert_eq!(
            find_transcript(projects.path(), "/work/greet", other_id),
            Some(other.join(format!("{other_id}.jsonl")))
        );

        assert_eq!(
            find_transcript(
                projects.path(),
                "/work/greet",
                "99999999-0000-0000-0000-000000000000"
            ),
            None
        );
        // Never a path: only a session id names a file.
        assert_eq!(
            find_transcript(projects.path(), "/work/greet", "../../etc/passwd"),
            None
        );
        assert_eq!(find_transcript(projects.path(), "/work/greet", ""), None);
        assert_eq!(
            find_transcript(&projects.path().join("missing"), "/work/greet", ID),
            None
        );
    }

    #[test]
    fn claude_code_s_folder_is_its_setting_or_the_home_one() {
        let home = Some(PathBuf::from("/home/me"));
        assert_eq!(
            config_dir_from(Some("/profiles/work".into()), home.clone()),
            Some(PathBuf::from("/profiles/work"))
        );
        assert_eq!(
            config_dir_from(Some("".into()), home.clone()),
            Some(PathBuf::from("/home/me").join(".claude"))
        );
        assert_eq!(
            config_dir_from(None, home),
            Some(PathBuf::from("/home/me").join(".claude"))
        );
        assert_eq!(config_dir_from(None, None), None);
    }

    #[test]
    fn a_session_s_history_or_nothing() {
        let projects = tempfile::tempdir().unwrap();
        let folder = projects
            .path()
            .join(crate::transcript::claude_project_dir_name("/work/greet"));
        fs::create_dir_all(&folder).unwrap();
        fs::write(folder.join(format!("{ID}.jsonl")), sample()).unwrap();
        assert_eq!(
            history_in(projects.path(), "/work/greet", ID)
                .unwrap()
                .len(),
            5
        );
        assert!(history_in(
            projects.path(),
            "/work/greet",
            "99999999-0000-0000-0000-000000000000"
        )
        .unwrap()
        .is_empty());
    }
}
